export const NOTIFICACAO_REPOSITORY = Symbol('NOTIFICACAO_REPOSITORY');
export const NOTIFICACAO_PREFERENCIA_REPOSITORY = Symbol('NOTIFICACAO_PREFERENCIA_REPOSITORY');
export const NOTIFICACAO_QUEUE = Symbol('NOTIFICACAO_QUEUE');
export const NOTIFICATION_QUEUE_NAME = 'notificacoes';
