export const SALA_TELEMEDICINA_REPOSITORY = Symbol('SALA_TELEMEDICINA_REPOSITORY');
export const SALA_EVENTO_REPOSITORY = Symbol('SALA_EVENTO_REPOSITORY');
export const SINAL_SALA_REPOSITORY = Symbol('SINAL_SALA_REPOSITORY');
